/*
 * MIT License
 *
 * Copyright (c) 2023 EndsOfTheEarth
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 **/
using QueryLite.DbSchema.Tables;
using System;
using System.Collections.Generic;

namespace QueryLite.DbSchema {

    public sealed class Schema {

        public List<DatabaseTable> Tables { get; }

        public Schema(List<DatabaseTable> tables) {
            Tables = tables;
        }
    }

    public sealed class DatabaseTable {

        public StringKey<ISchemaName> Schema { get; }
        public StringKey<ITableName> TableName { get; }
        public bool IsView { get; }
        public string Description { get; }  //TODO: Populate
        public List<DatabaseColumn> Columns { get; } = new List<DatabaseColumn>();

        public DatabaseTable(StringKey<ISchemaName> schema, StringKey<ITableName> tableName, bool isView, string description) {
            Schema = schema;
            TableName = tableName;
            IsView = isView;
            Description = description;
        }

        public override string ToString() {
            return Schema.ToString() + "." + TableName.ToString();
        }
    }

    public sealed class DatabaseColumn {

        public DatabaseTable Table { get; }
        public StringKey<IColumnName> ColumnName { get; }
        public DataType DataType { get; }
        public bool IsPrimaryKey { get; internal set; }
        public string PrimaryKeyConstraintName { get; internal set; } = string.Empty;
        public int? Length { get; }
        public bool IsNullable { get; }

        public bool IsAutoGenerated { get; }
        public string Description { get; } = string.Empty;  //TODO: Populate
        public bool IsForeignKey { get; internal set; }
        public string ForeignKeyConstraintName { get; internal set; } = string.Empty;
        public DatabaseTable? ForeignKeyTable { get; internal set; }

        public DatabaseColumn(DatabaseTable table, StringKey<IColumnName> columnName, DataType dataType, int? length, bool isNullable, bool isAutoGenerated) {
            Table = table;
            ColumnName = columnName;
            DataType = dataType;
            Length = length;
            IsNullable = isNullable;
            IsAutoGenerated = isAutoGenerated;
        }
        public override string ToString() {
            return Table.TableName.ToString() + "." + ColumnName + $" ({(DataType != null ? DataType.ToString() : "?")})";
        }
    }

    public sealed class DataType {

        public string Name { get; }
        public Type DotNetType { get; }

        public DataType(string name, Type dotNetType) {
            Name = name;
            DotNetType = dotNetType;
        }
        public override string ToString() {
            return $"{Name} {{{DotNetType}}}";
        }
    }
}