/*
 * MIT License
 *
 * Copyright (c) 2026 EndsOfTheEarth
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 **/
using Microsoft.Data.Sqlite;
using QueryLite.DbSchema.Tables.Sqlite;

namespace QueryLite.DbSchema {

    public sealed class SqliteSchemaLoader {

        public static List<DatabaseTable> LoadTables(IDatabase database) {

            SchemaTable schemaTable = SchemaTable.Instance;

            var result = Query
                .Select(
                    row => new {
                        TblName = row.Get(schemaTable.TblName),
                        Name = row.Get(schemaTable.Name),
                        Type = row.Get(schemaTable.Type)
                    }
                )
                .From(schemaTable)
                .Where(schemaTable.Type == "table")
                .Execute(database);

            List<DatabaseTable> tables = [];

            foreach(var row in result.Rows) {

                bool exclude = string.Equals(row.TblName, "sqlite_sequence", StringComparison.OrdinalIgnoreCase);

                if(exclude) {
                    continue;
                }
                DatabaseTable table = new DatabaseTable(
                    schema: SchemaName.Empty,
                    tableName: TableName.ValueOf(row.TblName),
                    isView: false
                );
                LoadTable(table, database);
                tables.Add(table);
            }
            return tables;
        }

        private static void LoadTable(DatabaseTable table, IDatabase database) {

            using SqliteConnection connection = (SqliteConnection)database.GetNewConnection();

            connection.Open();

            using SqliteCommand command = new(commandText: $"PRAGMA table_info('{table.TableName}');", connection);

            using SqliteDataReader reader = command.ExecuteReader();

            while(reader.Read()) {

                int cid = reader.GetInt32(reader.GetOrdinal("cid"));
                string name = reader.GetString(reader.GetOrdinal("name"));
                string type = reader.GetString(reader.GetOrdinal("type"));
                int notnull = reader.GetInt32(reader.GetOrdinal("notnull"));
                int pk = reader.GetInt32(reader.GetOrdinal("pk"));

                Type? dotNetType = SqliteTypes.GetDotNetType(type);

                DataType dataType = new DataType(name: type, dotNetType: (dotNetType ?? typeof(IUnknownType)));

                table.Columns.Add(
                    new DatabaseColumn(
                        table: table,
                        columnName: ColumnName.ValueOf(name),
                        dataType: dataType,
                        sqlDataTypeName: type,
                        length: null,
                        isNullable: notnull == 0,
                        isAutoGenerated: false
                    )
                );

                bool isPrimaryKey = pk > 0;

                if(isPrimaryKey) {
                    table.PrimaryKey ??= new DatabasePrimaryKey("");
                    table.PrimaryKey.ColumnNames.Add(name);
                }
            }
            connection.Close();
        }

        public static class SqliteTypes {

            private static readonly Dictionary<string, Type?> _Lookup = new Dictionary<string, Type?>(StringComparer.OrdinalIgnoreCase);

            static SqliteTypes() {

                _Lookup.Add("INTEGER", typeof(SqliteInteger));
                _Lookup.Add("REAL", typeof(SqliteReal));
                _Lookup.Add("TEXT", typeof(SqliteText));
                _Lookup.Add("BLOB", typeof(SqliteBlob));

            }
            public static Type? GetDotNetType(string typeName) {

                if(!_Lookup.TryGetValue(typeName, out Type? dotNetType)) {
                    return null;
                }
                return dotNetType;
            }
        }
    }
    public sealed class SqliteInteger;
    public sealed class SqliteReal;
    public sealed class SqliteText;
    public sealed class SqliteBlob;
}