using QueryLite;
using QueryLite.Utility;

namespace QueryLiteTest.Tables {

    public interface IRowVersionTest { }

    public sealed class RowVersionTestTable : ATable {

        public static readonly RowVersionTestTable Instance = new RowVersionTestTable();

        public Column<IntKey<IRowVersionTest>> Id { get; }
        public Column<string> TextValue { get; }
        public Column<byte[]> RowVersion { get; }

        public override PrimaryKey? PrimaryKey => new PrimaryKey(table: this, constraintName: "pk_RowVersionTest", Id);

        private RowVersionTestTable() : base(tableName: "RowVersionTest", schemaName: "dbo") {

            Id = new Column<IntKey<IRowVersionTest>>(this, columnName: "Id");
            TextValue = new Column<string>(this, columnName: "TextValue", length: 10);
            RowVersion = new Column<byte[]>(this, columnName: "RowVersion", isAutoGenerated: true, length: int.MaxValue);
        }
    }
}