using QueryLite;

namespace QueryLiteTest.Tables {

    public interface IRowVersionTest { }

    public sealed class RowVersionTestTable : ATable {

        public static readonly RowVersionTestTable Instance = new();

        public Column<RowVersionId, int> Id { get; }
        public Column<string> TextValue { get; }
        public Column<byte[]> RowVersion { get; }

        public override PrimaryKey? PrimaryKey => new(table: this, name: "pk_RowVersionTest", Id);

        private RowVersionTestTable() : base(name: "RowVersionTest", schemaName: "dbo") {

            Id = new Column<RowVersionId, int>(this, name: "Id");
            TextValue = new Column<string>(this, name: "TextValue", length: new(10));
            RowVersion = new Column<byte[]>(this, name: "RowVersion", isAutoGenerated: true);
        }
    }
}